server:
  port: 9000
spring:
  kafka:
    consumer:
      group-id: trade_message_processor
      auto-offset-reset: earliest
    bootstrap-servers: 127.0.0.1:9092

trade-processor:
  topic-name: trade_message
  messages-per-request: 10

auto:
  create:
    topics:
      enable: true

